### ISSUE TITLE
Fails to build with LLD 7.0

### ISSUE THREAD

**Issue by jbeich** [swaywm/wlroots#1450]
Development version of FreeBSD recently [upgraded](https://svnweb.freebsd.org/changeset/base/342123) its toolchain to one based on LLVM 7.0.1 which broke this project. Maybe related to an [upstream LLD bug](https://bugs.llvm.org/show_bug.cgi?id=38549).

```
$ pkg install git meson pkgconf wayland-protocols libinput libxkbcommon pixman mesa-libs
$ git clone https://github.com/swaywm/wlroots
$ cd wlroots
$ sed -i -e /examples/d meson.build
$ meson build
$ ninja -C build
[...]
ld: error: duplicate symbol 'wlr_signal_emit_safe' in version script
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```
Environment:
```
$ cc --version
FreeBSD clang version 7.0.1 (tags/RELEASE_701/final 349250) (based on LLVM 7.0.1)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
$ cc -Wl,--version
LLD 7.0.1 (FreeBSD 349250-1300001) (compatible with GNU linkers)
```
Workaround:
```
$ pkg install llvm60
$ LDFLAGS="$LDFLAGS -fuse-ld=lld60" meson build --wipe
$ ninja -C build
```
```
$ pkg install binutils
$ LDFLAGS="$LDFLAGS -fuse-ld=bfd" meson build --wipe
$ ninja -C build
```

**Comment by emersion** [comment]
Seems LLD doesn't handle wildcards properly.

**Comment by jbeich** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/e1ee3837acfe and backported in https://github.com/freebsd/freebsd/commit/acdff3ca6471.
