### ISSUE TITLE
examples: fails to build with ffmpeg >= 4.4 due to -Werror

### ISSUE THREAD

**Issue by jbeich** [swaywm/wlroots#2798]
Regressed by https://github.com/ffmpeg/ffmpeg/commit/f7db77bd8785d1715d3e7ed7e69bd1cc991f2d07

```c
examples/dmabuf-capture.c:494:4: error: 'av_init_packet' is deprecated [-Werror,-Wdeprecated-declarations]
                        av_init_packet(&pkt);
                        ^
/usr/include/libavcodec/packet.h:487:1: note: 'av_init_packet' has been explicitly marked deprecated here
attribute_deprecated
^
/usr/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
```

**Comment by emersion** [comment]
https://github.com/swaywm/wlroots/pull/2799
